from pathlib import Path
import argparse

from PIL import Image, ImageOps
import torch
from torch import nn
from torchvision import models, transforms


def main():
    parser = argparse.ArgumentParser(
        description="Classify an image as airport or non-airport."
    )
    parser.add_argument(
        "--image",
        type=Path,
        required=True,
        help="Path to the input image.",
    )
    parser.add_argument(
        "--checkpoint",
        type=Path,
        required=True,
        help="Path to the trained model checkpoint.",
    )
    args = parser.parse_args()

    if not args.image.is_file():
        raise FileNotFoundError(f"Image not found: {args.image}")

    if not args.checkpoint.is_file():
        raise FileNotFoundError(
            f"Checkpoint not found: {args.checkpoint}"
        )

    device = torch.device(
        "cuda" if torch.cuda.is_available() else "cpu"
    )

    # Load the checkpoint generated by our training script.
    checkpoint = torch.load(
        args.checkpoint,
        map_location="cpu",
        weights_only=True,
    )

    class_to_idx = checkpoint["class_to_idx"]
    idx_to_class = {
        index: name for name, index in class_to_idx.items()
    }

    # Restore the trained classifier without downloading weights.
    model = models.resnet18(weights=None)
    model.fc = nn.Linear(
        model.fc.in_features,
        len(class_to_idx),
    )
    model.load_state_dict(checkpoint["model_state_dict"])
    model = model.to(device)
    model.eval()

    # Match the preprocessing used for validation and testing.
    transform = transforms.Compose([
        transforms.Resize(tuple(checkpoint["image_size"])),
        transforms.ToTensor(),
        transforms.Normalize(
            mean=checkpoint["mean"],
            std=checkpoint["std"],
        ),
    ])

    # Apply EXIF orientation and convert the image to RGB.
    with Image.open(args.image) as source:
        image = ImageOps.exif_transpose(source).convert("RGB")

    # Add a batch dimension: [3, H, W] -> [1, 3, H, W].
    image_tensor = transform(image).unsqueeze(0).to(device)

    with torch.inference_mode():
        outputs = model(image_tensor)
        probabilities = torch.softmax(outputs, dim=1)[0]
        predicted_index = probabilities.argmax().item()

    print("Image:", args.image.resolve())
    print("Device:", device)
    print("Model epoch:", checkpoint["epoch"])
    print("Prediction:", idx_to_class[predicted_index])
    print()

    for index in sorted(idx_to_class):
        print(
            f"{idx_to_class[index]} score: "
            f"{probabilities[index].item():.2%}"
        )

    print("\nScores are model outputs, not guaranteed correctness.")


if __name__ == "__main__":
    main()